### ISSUE TITLE
Cannot enqueue Query after invoking quit

### ISSUE THREAD

**Issue by alx** [JohnMcLear/draw#184]
On a fresh install with apparently nothing wrong.

```
etherpad-lite@web:/var/www/draw.tetalab.org$ ./bin/run.sh 
Ensure that all dependencies are up to date...
start...
Access Etherdraw at http://127.0.0.19002
made room
load from db
Initting db

/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
Error: Cannot enqueue Query after invoking quit.
    at Protocol._validateEnqueue (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:196:16)
    at Protocol._enqueue (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at Connection.query (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:185:25)
    at /var/www/draw.tetalab.org/node_modules/ueberDB/mysql_db.js:86:12
    at Query._callback (/var/www/draw.tetalab.org/node_modules/ueberDB/mysql_db.js:116:5)
    at Query.Sequence.end (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/var/www/draw.tetalab.org/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
```

**Comment by JohnMcLear** [comment]
Please read: http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by alx** [comment]
How to replicate : create a fresh etherdraw install, configure settings.json with mysql database, launch ```bin/run.sh```

* Expected behavior: http://120.0.0.1:9002/ create a new draw pad where it's possible to draw
* Actual behavior: http://120.0.0.1:9002/ is opening, freezing with "Loading existing sketch... Click and hold to access the colour wheel" message, and the server is crashing with first comment error

Dirty db settings are working, using it until I can find more information about this issue.

* System : debian jessy, node v0.10.36
* settings.json : 
```
  "dbType" : "mysql",
  "dbSettings" : {
    "user"    : "root", 
    "host"    : "localhost", 
    "password": "", 
    "database": "etherdraw"
  }
```
* database ```etherdraw``` exists in mysql, and ```store``` table was created during first run

**Comment by JohnMcLear** [comment]
Try update node please.  Sounds like a dep issue
----- Reply message -----

**Comment by JohnMcLear** [comment]
Latest node?
----- Reply message -----

**Comment by alx** [comment]
Yes, latest node : http://nodejs.org/ Current Version: v0.10.36

**Comment by alx** [comment]
If it can help, etherpad is working fine on the same machine with mysql settings.

**Comment by JohnMcLear** [comment]
Okay must be a db config issue with lTest ueberdb try roll back ueberdb a few minor versions and test that..



----- Reply message -----

**Comment by JohnMcLear** [comment]
Closing due to lack of activity

**Comment by shadowcodex** [comment]
Having the same issue, did we ever figure out what the issue was?

**Comment by p-thurner** [comment]
I'm also experiencing this issue.

**Comment by p-thurner** [comment]
I'm getting the same result when using the "dirty" db type.
