### ISSUE TITLE
Can't deploy to Openshift

### ISSUE THREAD

**Issue by MrSwiss** [JohnMcLear/draw#225]
This is a log when I try to run application

Do you have any suggestions?

```
DEBUG: Running node-supervisor with
DEBUG:   program 'server.js'
DEBUG:   --watch '/var/lib/openshift/56a2280589f5cf717d000111/app-root/data/.nodewatch'
DEBUG:   --ignore 'undefined'
DEBUG:   --extensions 'node|js|coffee'
DEBUG:   --exec 'node'
DEBUG: Starting child process with 'node server.js'
DEBUG: Watching directory '/var/lib/openshift/56a2280589f5cf717d000111/app-root/data/.nodewatch' for changes.
Warning: express.createServer() is deprecated, express
applications no longer inherit from http.Server,
please use:
  var express = require("express");
  var app = express();
Fri Jan 22 2016 08:02:09 GMT-0500 (EST): Node server started on 127.5.140.129:8080 ...
DEBUG: Sending SIGTERM to child...
Fri Jan 22 2016 08:04:26 GMT-0500 (EST): Received SIGTERM - terminating sample app ...
Fri Jan 22 2016 08:04:26 GMT-0500 (EST): Node server stopped.
DEBUG: Running node-supervisor with
DEBUG:   program 'server.js'
DEBUG:   --watch '/var/lib/openshift/56a2280589f5cf717d000111/app-root/data/.nodewatch'
DEBUG:   --ignore 'undefined'
DEBUG:   --extensions 'node|js|coffee'
DEBUG:   --exec 'node'
DEBUG: Starting child process with 'node server.js'
DEBUG: Watching directory '/var/lib/openshift/56a2280589f5cf717d000111/app-root/data/.nodewatch' for changes.
DirtyDB is used. This is fine for testing but not recommended for production.
PORT:8080
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Access Etherdraw at http://127.5.140.129:8080
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Function.app.listen (/var/lib/openshift/56a2280589f5cf717d000111/app-root/runtime/repo/node_modules/express/lib/application.js:533:24)
    at Object.<anonymous> (/var/lib/openshift/56a2280589f5cf717d000111/app-root/runtime/repo/server.js:35:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
DEBUG: Program node server.js exited with code 8
```

**Comment by JohnMcLear** [comment]
Don't be lazy.  Read the error
----- Reply message -----

**Comment by MrSwiss** [comment]
Thank you, I think that binding wrong ip/port causing the error.

**Comment by MrSwiss** [comment]
Thank you, I think that binding wrong ip/port causing the error.
