### ISSUE TITLE
How Activate SSL?

### ISSUE THREAD

**Issue by batmanofficial** [JohnMcLear/draw#254]
How activate ssl?

tranks

**Comment by eltntawy** [comment]
i am interested also please help

**Comment by bytesnz** [comment]
Configure the certificates in the settings.json file https://github.com/JohnMcLear/draw/blob/master/settings.json.template#L34 (https://github.com/JohnMcLear/draw/blob/master/server.js)

**Comment by eltntawy** [comment]
thank you


--
Best Regards,

*Mohamed Refaat*

BSc. in Computer Science
Faculty of Science, Cairo University
Mobile : +20 1092739346
Blog : about.me/eltntawy <http://www.about.me/eltntawy>

**Comment by eltntawy** [comment]
@bytesnz did you know where can i configure the whiteboard files to upload them as pdf

**Comment by batmanofficial** [comment]
@bytesnz Tranks :) :):):):)

**Comment by batmanofficial** [comment]
I tried it but it does not work, can you edit it to see?

**Comment by batmanofficial** [comment]
why is this error?

SSL Enabled
SSL Key Fileconfig/sslcerts/hola/key.pem
SSL Cert Auth Fileconfig/sslcerts/hola/cert.pem
Access Etherdraw at http://0.0.0.0:9002

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1133:5)
    at Object.<anonymous> (/var/www/html/draw/server.js:31:49)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)


@bytesnz
