### ISSUE TITLE
Could not locate bindings file

### ISSUE THREAD

**Issue by carlesm95** [JohnMcLear/draw#256]
Hi,
I'm on Ubuntu Mate 16.04 and I'm getting this error when running run.sh:

/srv/draw/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /srv/draw/node_modules/contextify/build/contextify.node
 → /srv/draw/node_modules/contextify/build/Debug/contextify.node
 → /srv/draw/node_modules/contextify/build/Release/contextify.node
 → /srv/draw/node_modules/contextify/out/Debug/contextify.node
 → /srv/draw/node_modules/contextify/Debug/contextify.node
 → /srv/draw/node_modules/contextify/out/Release/contextify.node
 → /srv/draw/node_modules/contextify/Release/contextify.node
 → /srv/draw/node_modules/contextify/build/default/contextify.node
 → /srv/draw/node_modules/contextify/compiled/7.9.0/linux/x64/contextify.node
    at bindings (/srv/draw/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/srv/draw/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/draw/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)

Can anyone help me?

Thanks.

**Comment by underdoeg** [comment]
I have the same issue on debian 8
